require("config.options")
require("config.colorScheme")
require("config.global")
require("config.diagnostic")
require("config.keymap")
require("core.lazy")
require("config.lsp")
require("config.user_command")
